# Data Manipulation (NumPy + Pandas) — Overview

**Purpose:** Practical ETL-style transformations combining NumPy and Pandas for feature engineering and data cleaning.

**How to use this notebook:** Note conversions between `DataFrame` and NumPy arrays and prefer vectorized column operations where possible.

**Interview tips:** Explain when `apply` is appropriate vs vectorized ops; discuss memory trade-offs when converting structures.

## Data Manipulation and Analysis with Pandas

Data manipulation and analysis are key tasks in any data science or data analysis project. Pandas provides a wide range of functions for data manipulation and analysis, making it easier to clean, transform and extract insights from data.

In [23]:
import pandas as pd

In [24]:
df = pd.read_csv('employees.csv')

print(f"First 5 rows of the dataset are: \n{df.head(5)}")
print(f"\nLast 5 rows of the dataset are : \n{df.tail(5)}")

First 5 rows of the dataset are:
   id     name   age   department   salary
0   1    Alice  25.0           HR  50000.0
1   2      Bob  30.0  Engineering  70000.0
2   3  Charlie  28.0    Marketing  55000.0
3   4    Diana  35.0  Engineering  80000.0
4   5    Ethan  40.0      Finance  90000.0

Last 5 rows of the dataset are :
    id   name   age   department   salary
25  26   Zack  37.0           HR  59000.0
26  27  Amber  29.0    Marketing  56000.0
27  28  Brian  40.0      Finance      NaN
28  29   Cara  32.0  Engineering  77000.0
29  30  David   NaN           HR  53000.0

In [25]:
# Finding missing values in the dataset

print(f"Checking whether each column has at least one null value or not: \n{df.isnull().any()}")
print(f"\nNumber of null values in each column is : \n{df.isnull().sum()}")

Checking whether each column has at least one null value or not:
id            False
name          False
age            True
department    False
salary         True
dtype: bool

Number of null values in each column is :
id            0
name          0
age           2
department    0
salary        4
dtype: int64

In [26]:
# Filling all null values with 0

df_filled_zeros = df.fillna(0)
df_filled_zeros

    id     name   age   department   salary
0    1    Alice  25.0           HR  50000.0
1    2      Bob  30.0  Engineering  70000.0
2    3  Charlie  28.0    Marketing  55000.0
3    4    Diana  35.0  Engineering  80000.0
4    5    Ethan  40.0      Finance  90000.0
5    6    Fiona  29.0           HR  52000.0
6    7   George  32.0    Marketing  60000.0
7    8    Helen  27.0      Finance  58000.0
8    9      Ian  33.0  Engineering  75000.0
9   10    Julia  26.0           HR  51000.0
10  11    Kevin  31.0    Marketing      0.0
11  12    Linda   0.0      Finance  62000.0
12  13     Mark  45.0  Engineering  95000.0
13  14     Nina  38.0           HR  56000.0
14  15    Oscar  29.0    Marketing  57000.0
15  16    Paula  34.0      Finance  88000.0
16  17  Quentin  36.0  Engineering      0.0
17  18   Rachel  28.0           HR  54000.0
18  19      Sam  41.0    Marketing  61000.0
19  20     Tina  30.0      Finance  60000.0
20  21      Uma  27.0  Engineering  72000.0
21  22  Vincent  39.0           HR      0.0
22  23    Wendy  33.0    Marketing  58000.0
23  24   Xavier  42.0      Finance  91000.0
24  25     Yara  25.0  Engineering  68000.0
25  26     Zack  37.0           HR  59000.0
26  27    Amber  29.0    Marketing  56000.0
27  28    Brian  40.0      Finance      0.0
28  29     Cara  32.0  Engineering  77000.0
29  30    David   0.0           HR  53000.0

In [27]:
# Filling all null values with the mean of that column
df_filled_with_mean = df

df_filled_with_mean['salary'] = df['salary'].fillna(df['salary'].mean())
df_filled_with_mean['age'] = df['age'].fillna(df['age'].mean())

df_filled_with_mean

    id     name        age   department        salary
0    1    Alice  25.000000           HR  50000.000000
1    2      Bob  30.000000  Engineering  70000.000000
2    3  Charlie  28.000000    Marketing  55000.000000
3    4    Diana  35.000000  Engineering  80000.000000
4    5    Ethan  40.000000      Finance  90000.000000
5    6    Fiona  29.000000           HR  52000.000000
6    7   George  32.000000    Marketing  60000.000000
7    8    Helen  27.000000      Finance  58000.000000
8    9      Ian  33.000000  Engineering  75000.000000
9   10    Julia  26.000000           HR  51000.000000
10  11    Kevin  31.000000    Marketing  65692.307692
11  12    Linda  32.892857      Finance  62000.000000
12  13     Mark  45.000000  Engineering  95000.000000
13  14     Nina  38.000000           HR  56000.000000
14  15    Oscar  29.000000    Marketing  57000.000000
15  16    Paula  34.000000      Finance  88000.000000
16  17  Quentin  36.000000  Engineering  65692.307692
17  18   Rachel  28.000000           HR  54000.000000
18  19      Sam  41.000000    Marketing  61000.000000
19  20     Tina  30.000000      Finance  60000.000000
20  21      Uma  27.000000  Engineering  72000.000000
21  22  Vincent  39.000000           HR  65692.307692
22  23    Wendy  33.000000    Marketing  58000.000000
23  24   Xavier  42.000000      Finance  91000.000000
24  25     Yara  25.000000  Engineering  68000.000000
25  26     Zack  37.000000           HR  59000.000000
26  27    Amber  29.000000    Marketing  56000.000000
27  28    Brian  40.000000      Finance  65692.307692
28  29     Cara  32.000000  Engineering  77000.000000
29  30    David  32.892857           HR  53000.000000

In [28]:
# Renaming  columns

df = df.rename(columns={'salary':'inhand_salary'})
df.head()

   id     name   age   department  inhand_salary
0   1    Alice  25.0           HR        50000.0
1   2      Bob  30.0  Engineering        70000.0
2   3  Charlie  28.0    Marketing        55000.0
3   4    Diana  35.0  Engineering        80000.0
4   5    Ethan  40.0      Finance        90000.0

In [29]:
# Converting data type of a column

df['int_salary'] = df['inhand_salary'].astype(int)
df.head()

   id     name   age   department  inhand_salary  int_salary
0   1    Alice  25.0           HR        50000.0       50000
1   2      Bob  30.0  Engineering        70000.0       70000
2   3  Charlie  28.0    Marketing        55000.0       55000
3   4    Diana  35.0  Engineering        80000.0       80000
4   5    Ethan  40.0      Finance        90000.0       90000

In [30]:
# Finding yearly salary

df['annual_salary'] = df['inhand_salary'].apply(lambda x : x * 12)
df.head()

   id     name   age   department  inhand_salary  int_salary  annual_salary
0   1    Alice  25.0           HR        50000.0       50000       600000.0
1   2      Bob  30.0  Engineering        70000.0       70000       840000.0
2   3  Charlie  28.0    Marketing        55000.0       55000       660000.0
3   4    Diana  35.0  Engineering        80000.0       80000       960000.0
4   5    Ethan  40.0      Finance        90000.0       90000      1080000.0

### Data aggregating and grouping

In [31]:
grouped_mean = df.groupby('department')['annual_salary'].mean()
print(f"Mean annual salary for each department is : \n{grouped_mean}")

Mean annual salary for each department is :
department
Engineering    904038.461538
Finance        882329.670330
HR             661038.461538
Marketing      707472.527473
Name: annual_salary, dtype: float64

In [35]:
# Multiple column grouping

grouped_mean = df.groupby(['department','name'])['inhand_salary'].mean()
grouped_mean

department   name
Engineering  Bob        70000.000000
             Cara       77000.000000
             Diana      80000.000000
             Ian        75000.000000
             Mark       95000.000000
             Quentin    65692.307692
             Uma        72000.000000
             Yara       68000.000000
Finance      Brian      65692.307692
             Ethan      90000.000000
             Helen      58000.000000
             Linda      62000.000000
             Paula      88000.000000
             Tina       60000.000000
             Xavier     91000.000000
HR           Alice      50000.000000
             David      53000.000000
             Fiona      52000.000000
             Julia      51000.000000
             Nina       56000.000000
             Rachel     54000.000000
             Vincent    65692.307692
             Zack       59000.000000
Marketing    Amber      56000.000000
             Charlie    55000.000000
             George     60000.000000
             Kevin      65692.307692
             Oscar      57000.000000
             Sam        61000.000000
             Wendy      58000.000000
Name: inhand_salary, dtype: float64

In [36]:
# Multiple aggregators

grouped_aggregation = df.groupby('department')['inhand_salary'].agg(['mean','sum','count'])
print(f"Different inhand_salary aggregation values after grouping by department is : \n{grouped_aggregation}")

Different inhand_salary aggregation values after grouping by department is :
                     mean            sum  count
department
Engineering  75336.538462  602692.307692      8
Finance      73527.472527  514692.307692      7
HR           55086.538462  440692.307692      8
Marketing    58956.043956  412692.307692      7

### Merging and joining data

In [37]:
df1 = pd.DataFrame({'key':['A','B','C','D'],'value1':[1,2,3,4]})
df2 = pd.DataFrame({'key':['A','C','D','E'],'value2':[9,10,11,12]})

print(f"DataFrame df1 is : \n{df1}")
print(f"\nDataFrame df2 is : \n{df2}")

DataFrame df1 is :
  key  value1
0   A       1
1   B       2
2   C       3
3   D       4

DataFrame df2 is :
  key  value2
0   A       9
1   C      10
2   D      11
3   E      12

In [39]:
# Merge df using inner join using key
# Since we use inner join, we will only get common rows where keys match

pd.merge(df1,df2,on='key',how='inner')

  key  value1  value2
0   A       1       9
1   C       3      10
2   D       4      11

In [40]:
# Merging dataframes using outer join using key
# Since we are performing outer join, we will get both common and unique elements of both dataframes

pd.merge(df1,df2,on='key',how='outer')

  key  value1  value2
0   A     1.0     9.0
1   B     2.0     NaN
2   C     3.0    10.0
3   D     4.0    11.0
4   E     NaN    12.0

In [ ]:
# Merging both dataframes using left outer join on 'key'
# Since we are performing left_outer join, we will get common key values of both dataframes and unique values of left dataframe

pd.merge(df1,df2,on='key',how='left')

  key  value1  value2
0   A       1     9.0
1   B       2     NaN
2   C       3    10.0
3   D       4    11.0

In [42]:
# Merging both dataframes using right outer join on 'key'
# We will get common 'key' fields from both dataframes and unique values of right dataframe

pd.merge(df1,df2,on='key',how='right')

  key  value1  value2
0   A     1.0       9
1   C     3.0      10
2   D     4.0      11
3   E     NaN      12