### Data encoding

Data encoding is a technique to convert categorical data into numerical values so that machines can understand them.
1. Nominal/OHE encoding
2. Label and ordinal encoding
3. Target guided ordinal encoding

### Nominal/OHE encoding

One hot encoding, also known as nominal encoding is a technique used to represent categorical data as numerical data, which is more suitable for machine learning algorithms. In this technique, each category is represented as a binary vector where each bit corresponds to a unique category. For example, if we have a categorical variable "color" with three possible values (red, green and blue), we can represent it in one hot encoding as follows:

1. Red: [1,0,0]
2. Green [0,1,0]
3. Blue [0,0,1]

#### Drawback of One Hot Encoding / Nominal Encoding

One‑Hot Encoding transforms categorical variables into binary vectors. While effective for small sets of categories, it has a significant limitation:

- High Dimensionality: When a categorical feature contains a large number of unique values (high cardinality), One‑Hot Encoding produces a very large, sparse matrix.
- Sparsity Issues: Most entries in the encoded matrix are zeros, which increases memory usage and computational overhead.
- Risk of Overfitting: Machine learning models may overfit to noise in such high‑dimensional data, reducing generalization performance.
- Reduced Efficiency: Training and inference become slower due to the inflated feature space.

Because of these drawbacks, One‑Hot Encoding is generally not recommended for categorical variables with many unique values.

In [1]:
import pandas as pd 
from sklearn.preprocessing import OneHotEncoder

In [2]:
df = pd.DataFrame({
    'color': ['red','blue','green','red','blue']
})
df.head()

   color
0    red
1   blue
2  green
3    red
4   blue

In [3]:
# Create an instance of OneHotEncoder

encoder = OneHotEncoder()

In [6]:
encoded_data = encoder.fit_transform(df[['color']]).toarray()

In [7]:
encoded_df = pd.DataFrame(encoded_data,columns=encoder.get_feature_names_out())
encoded_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0
4         1.0          0.0        0.0

In [8]:
encoder.transform([['blue']]).toarray()

c:\Users\SRIDATTA CHARAN\Desktop\Github\DS-ML-DL-NLP\env\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [9]:
pd.concat([df,encoded_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3    red         0.0          0.0        1.0
4   blue         1.0          0.0        0.0

### Using dataset

In [12]:
import seaborn as sns
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [15]:
encoded_days = encoder.fit_transform(df[['day']]).toarray()
encoded_days[:5]

array([[0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.]])

In [16]:
encoded_df = pd.DataFrame(encoded_days,columns=encoder.get_feature_names_out())
encoded_df

     day_Fri  day_Sat  day_Sun  day_Thur
0        0.0      0.0      1.0       0.0
1        0.0      0.0      1.0       0.0
2        0.0      0.0      1.0       0.0
3        0.0      0.0      1.0       0.0
4        0.0      0.0      1.0       0.0
..       ...      ...      ...       ...
239      0.0      1.0      0.0       0.0
240      0.0      1.0      0.0       0.0
241      0.0      1.0      0.0       0.0
242      0.0      1.0      0.0       0.0
243      0.0      0.0      0.0       1.0

[244 rows x 4 columns]

In [17]:
combined_df = pd.concat([df,encoded_df],axis=1)
combined_df.head()

,total_bill,tip,sex,smoker,day,time,size,day_Fri,day_Sat,day_Sun,day_Thur
0,16.99,1.01,Female,No,Sun,Dinner,2,0.0,0.0,1.0,0.0
1,10.34,1.66,Male,No,Sun,Dinner,3,0.0,0.0,1.0,0.0
2,21.01,3.50,Male,No,Sun,Dinner,3,0.0,0.0,1.0,0.0
3,23.68,3.31,Male,No,Sun,Dinner,2,0.0,0.0,1.0,0.0
4,24.59,3.61,Female,No,Sun,Dinner,4,0.0,0.0,1.0,0.0